// demo-snippets/vue3/SelectionDragDrop.vue
<!--
    Selection + Drag/Drop Demo (Vue 3 Composition API)

    This demo demonstrates how to mix selection mode (using long press) with drag-and-drop
    functionality without using reorderLongPressEnabled property.

    Features:
    - Long press on an item waits briefly to detect if a drag gesture starts
    - If no drag movement is detected within 200ms → starts selection mode
    - If drag movement is detected → starts CollectionView drag/reorder mode
    - In selection mode, tapping items toggles their selection
    - Exiting selection mode when no items are selected
    - Visual feedback with opacity changes for selected items

    Implementation approach:
    - Uses @longPress event to detect initial long press
    - Uses @pan event to detect drag movement (more efficient than @touch)
    - Pan events are only processed when a long press is active
    - Uses a timer to wait for drag movement after long press
    - Manually calls startDragging() to initiate CollectionView reorder
    - Maintains state for selectedItems, selectionMode, and drag tracking
-->
<template>
    <Page>
        <ActionBar :title="selectionMode ? selectedItems.value.length + ' items selected' : 'Selection + Drag/Drop'">
            <ActionItem v-if="selectionMode" ios.systemIcon="3" ios.position="right" text="Clear" @tap="exitSelectionMode" />
        </ActionBar>

        <GridLayout>
            <CollectionView
                ref="collectionView"
                :items="itemList"
                itemIdGenerator="color"
                rowHeight="100"
                reorderEnabled
                :reorderLongPressEnabled="false"
                @itemReorderStarting="onItemReorderStarting"
                @itemReordered="onItemReordered"
            >
                <template #default="{ item }">
                    <GridLayout
                        id="itemContainer"
                        rows="*, auto"
                        :backgroundColor="item.color"
                        :opacity="isSelected(item) ? 0.7 : 1"
                        @longPress="onLongPress(item, $event)"
                        @pan="onPan(item, $event)"
                        @tap="onItemTap(item, $event)"
                    >
                        <StackLayout row="1" class="item">
                            <Label row="1" :text="item.name" class="title" />
                            <Label row="1" :text="item.color" class="subtitle" />
                            <Label v-if="isSelected(item)" text="✓ SELECTED" class="selected-indicator" />
                        </StackLayout>
                    </GridLayout>
                </template>
            </CollectionView>
        </GridLayout>
    </Page>
</template>

<script setup lang="ts">
import { ContentView, ObservableArray } from '@nativescript/core';
import { ref } from 'nativescript-vue';

const collectionView = ref();
const itemList = ref(
    new ObservableArray([
        { type: 'item', name: 'TURQUOISE', color: '#1abc9c' },
        { type: 'item', name: 'EMERALD', color: '#2ecc71' },
        { type: 'item', name: 'PETER RIVER', color: '#3498db' },
        { type: 'item', name: 'AMETHYST', color: '#9b59b6' },
        { type: 'item', name: 'GREEN SEA', color: '#16a085' },
        { type: 'item', name: 'NEPHRITIS', color: '#27ae60' },
        { type: 'item', name: 'BELIZE HOLE', color: '#2980b9' },
        { type: 'item', name: 'ASBESTOS', color: '#7f8c8d' },
        { type: 'item', name: 'MIDNIGHT BLUE', color: '#2c3e50' },
        { type: 'item', name: 'SUN FLOWER', color: '#f1c40f' },
        { type: 'item', name: 'CARROT', color: '#e67e22' },
        { type: 'item', name: 'POMEGRANATE', color: '#c0392b' },
        { type: 'item', name: 'CLOUDS', color: '#ecf0f1' },
        { type: 'item', name: 'CONCRETE', color: '#95a5a6' },
        { type: 'item', name: 'ORANGE', color: '#f39c12' },
        { type: 'item', name: 'PUMPKIN', color: '#d35400' }
    ])
);

const selectedItems = ref([]);
const selectionMode = ref(false);
const longPressTimer = ref(null);
const dragStarted = ref(false);
const currentLongPressItem = ref(null);

function isSelected(item) {
    return selectedItems.value.some((selected) => selected.color === item.color);
}

function toggleSelection(item) {
    const index = selectedItems.value.findIndex((selected) => selected.color === item.color);
    if (index >= 0) {
        selectedItems.value.splice(index, 1);
    } else {
        selectedItems.value.push(item);
    }

    // Exit selection mode if no items are selected
    if (selectedItems.value.length === 0) {
        exitSelectionMode();
    }
}

function exitSelectionMode() {
    selectionMode.value = false;
    selectedItems.value = [];
}

function onItemTap(item, event) {
    if (selectionMode.value) {
        // In selection mode, tapping toggles selection
        toggleSelection(item);
    }
}

function onLongPress(item, event) {
    console.log('onLongPress detected for', item.name);
    if (selectionMode.value) {
        toggleSelection(item);
        return;
    }
    // Clear any existing timer
    if (longPressTimer.value) {
        clearTimeout(longPressTimer.value);
    }

    currentLongPressItem.value = item;
    dragStarted.value = false;

    // Wait a bit (200ms) to see if drag movement starts
    // This implements the logic: "if longpress is detected wait a bit"
    longPressTimer.value = setTimeout(() => {
        if (!dragStarted.value && currentLongPressItem.value) {
            // No drag detected, start selection mode
            // This implements: "if no drag => start selection"
            console.log('No drag detected - starting selection mode for', item.name);
            selectionMode.value = true;
            toggleSelection(item);
        }
        currentLongPressItem.value = null;
    }, 200);
}

function onPan(item, event) {
    // Only process pan events if we're tracking a long press
    if (!currentLongPressItem.value) {
        return;
    }

    // Pan gesture states: 0=began, 1=changed(panning), 2=ended, 3=cancelled
    // If we detect panning movement during long press, start dragging
    // This implements: "if drag was started => start collection view drag mode"
    if (event.state === 1 && !dragStarted.value) {
        // State 1: changed/panning
        console.log('Pan movement detected - starting drag mode for', item.name);
        dragStarted.value = true;

        // Clear the timer to prevent selection mode from starting
        if (longPressTimer.value) {
            clearTimeout(longPressTimer.value);
            longPressTimer.value = null;
        }

        // Start collection view drag/reorder mode
        // Get the touch point from the pan gesture
        const pointer = {
            getX: () => (event.ios ? event.ios.locationInView(null).x : event.android ? event.android.getX() : 0),
            getY: () => (event.ios ? event.ios.locationInView(null).y : event.android ? event.android.getY() : 0),
            id: 0
        };
        const index = itemList.value.indexOf(item);
        collectionView.value.$el.nativeView.startDragging(index, pointer);

        currentLongPressItem.value = null;
    } else if (event.state === 2 || event.state === 3) {
        // State 2: ended, State 3: cancelled
        // Reset state on pan end
        if (longPressTimer.value) {
            clearTimeout(longPressTimer.value);
            longPressTimer.value = null;
        }
        dragStarted.value = false;
        currentLongPressItem.value = null;
    }
}

function onItemReordered(e) {
    console.log('onItemReordered', e.index);
    (e.view as ContentView).content.opacity = 1;
}

function onItemReorderStarting(e) {
    console.log('onItemReorderStarting', e.index);
    (e.view as ContentView).content.opacity = 0.7;
}
</script>

<style scoped lang="scss">
ActionBar {
    background-color: #42b883;
}
.item {
    padding: 10;
    color: white;
    .title {
        font-size: 17;
        font-weight: bold;
    }
    .subtitle {
        font-size: 14;
    }
    .selected-indicator {
        font-size: 12;
        font-weight: bold;
        margin-top: 5;
    }
}
</style>

// demo-snippets/svelte/SelectionDragDrop.svelte
<style>
    ActionBar {
        background-color: #ff3e00;
    }
    .item {
        padding: 10;
        color: white;
    }
    .title {
        font-size: 17;
        font-weight: bold;
    }
    .subtitle {
        font-size: 14;
    }
    .selected-indicator {
        font-size: 12;
        font-weight: bold;
        margin-top: 5;
    }
</style>

<!--
    Selection + Drag/Drop Demo (Svelte)

    This demo demonstrates how to mix selection mode (using long press) with drag-and-drop
    functionality without using reorderLongPressEnabled property.

    Features:
    - Long press on an item waits briefly to detect if a drag gesture starts
    - If no drag movement is detected within 200ms → starts selection mode
    - If drag movement is detected → starts CollectionView drag/reorder mode
    - In selection mode, tapping items toggles their selection
    - Exiting selection mode when no items are selected
    - Visual feedback with opacity changes for selected items

    Implementation approach:
    - Uses on:longPress event to detect initial long press
    - Uses on:pan event to detect drag movement (more efficient than on:touch)
    - Pan events are only processed when a long press is active
    - Uses a timer to wait for drag movement after long press
    - Manually calls startDragging() to initiate CollectionView reorder
    - Maintains state for selectedItems, selectionMode, and drag tracking
-->
<script lang="ts">
    import { ContentView, ObservableArray } from '@nativescript/core';
    import { Template } from '@nativescript-community/svelte-native/components';

    let collectionView;
    const itemList = new ObservableArray([
        { type: 'item', name: 'TURQUOISE', color: '#1abc9c' },
        { type: 'item', name: 'EMERALD', color: '#2ecc71' },
        { type: 'item', name: 'PETER RIVER', color: '#3498db' },
        { type: 'item', name: 'AMETHYST', color: '#9b59b6' },
        { type: 'item', name: 'GREEN SEA', color: '#16a085' },
        { type: 'item', name: 'NEPHRITIS', color: '#27ae60' },
        { type: 'item', name: 'BELIZE HOLE', color: '#2980b9' },
        { type: 'item', name: 'ASBESTOS', color: '#7f8c8d' },
        { type: 'item', name: 'MIDNIGHT BLUE', color: '#2c3e50' },
        { type: 'item', name: 'SUN FLOWER', color: '#f1c40f' },
        { type: 'item', name: 'CARROT', color: '#e67e22' },
        { type: 'item', name: 'POMEGRANATE', color: '#c0392b' },
        { type: 'item', name: 'CLOUDS', color: '#ecf0f1' },
        { type: 'item', name: 'CONCRETE', color: '#95a5a6' },
        { type: 'item', name: 'ORANGE', color: '#f39c12' },
        { type: 'item', name: 'PUMPKIN', color: '#d35400' }
    ]);

    let selectedItems = [];
    let selectionMode = false;
    let longPressTimer = null;
    let dragStarted = false;
    let currentLongPressItem = null;

    function isSelected(item) {
        return selectedItems.some((selected) => selected.color === item.color);
    }

    function toggleSelection(item) {
        const index = selectedItems.findIndex((selected) => selected.color === item.color);
        if (index >= 0) {
            selectedItems.splice(index, 1);
        } else {
            selectedItems.push(item);
        }
        selectedItems = selectedItems; // Trigger reactivity

        // Exit selection mode if no items are selected
        if (selectedItems.length === 0) {
            exitSelectionMode();
        }
    }

    function exitSelectionMode() {
        selectionMode = false;
        selectedItems = [];
    }

    function onItemTap(item, event) {
        if (selectionMode) {
            // In selection mode, tapping toggles selection
            toggleSelection(item);
        }
    }

    function onLongPress(item, event) {
        console.log('onLongPress detected for', item.name);

        // Clear any existing timer
        if (longPressTimer) {
            clearTimeout(longPressTimer);
        }

        currentLongPressItem = item;
        dragStarted = false;

        // Wait a bit (200ms) to see if drag movement starts
        // This implements the logic: "if longpress is detected wait a bit"
        longPressTimer = setTimeout(() => {
            if (!dragStarted && currentLongPressItem) {
                // No drag detected, start selection mode
                // This implements: "if no drag => start selection"
                console.log('No drag detected - starting selection mode for', item.name);
                selectionMode = true;
                toggleSelection(item);
            }
            currentLongPressItem = null;
        }, 200);
    }

    function onPan(item, event) {
        // Only process pan events if we're tracking a long press
        if (!currentLongPressItem) {
            return;
        }

        // Pan gesture states: 0=began, 1=changed(panning), 2=ended, 3=cancelled
        // If we detect panning movement during long press, start dragging
        // This implements: "if drag was started => start collection view drag mode"
        if (event.state === 1 && !dragStarted) {
            // State 1: changed/panning
            console.log('Pan movement detected - starting drag mode for', item.name);
            dragStarted = true;

            // Clear the timer to prevent selection mode from starting
            if (longPressTimer) {
                clearTimeout(longPressTimer);
                longPressTimer = null;
            }

            // Start collection view drag/reorder mode
            // Get the touch point from the pan gesture
            const pointer = {
                getX: () => (event.ios ? event.ios.locationInView(null).x : event.android ? event.android.getX() : 0),
                getY: () => (event.ios ? event.ios.locationInView(null).y : event.android ? event.android.getY() : 0),
                id: 0
            };
            const index = itemList.indexOf(item);
            collectionView.startDragging(index, pointer);

            currentLongPressItem = null;
        } else if (event.state === 2 || event.state === 3) {
            // State 2: ended, State 3: cancelled
            // Reset state on pan end
            if (longPressTimer) {
                clearTimeout(longPressTimer);
                longPressTimer = null;
            }
            dragStarted = false;
            currentLongPressItem = null;
        }
    }

    function onItemReordered(e) {
        console.log('onItemReordered', e.index);
        (e.view as ContentView).content.opacity = 1;
    }

    function onItemReorderStarting(e) {
        console.log('onItemReorderStarting', e.index);
        (e.view as ContentView).content.opacity = 0.7;
    }
</script>

<page>
    <actionBar title={selectionMode ? selectedItems.length + ' items selected' : 'Selection + Drag/Drop'}>
        {#if selectionMode}
            <actionItem ios.position="right" ios.systemIcon="3" text="Clear" on:tap={exitSelectionMode} />
        {/if}
    </actionBar>

    <gridLayout>
        <collectionView
            bind:this={collectionView}
            itemIdGenerator="color"
            items={itemList}
            reorderEnabled={true}
            reorderLongPressEnabled={false}
            rowHeight="100"
            on:itemReorderStarting={onItemReorderStarting}
            on:itemReordered={onItemReordered}>
            <Template let:item>
                <gridLayout
                    id="itemContainer"
                    backgroundColor={item.color}
                    opacity={isSelected(item) ? 0.7 : 1}
                    rows="*, auto"
                    on:longPress={(event) => onLongPress(item, event)}
                    on:tap={(event) => onItemTap(item, event)}
                    on:pan={(event) => onPan(item, event)}>
                    <stackLayout class="item" row="1">
                        <label class="title" row="1" text={item.name} />
                        <label class="subtitle" row="1" text={item.color} />
                        {#if isSelected(item)}
                            <label class="selected-indicator" text="✓ SELECTED" />
                        {/if}
                    </stackLayout>
                </gridLayout>
            </Template>
        </collectionView>
    </gridLayout>
</page>
